name: chouchou
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Tes dépendances existantes
  cupertino_icons: ^1.0.6
  speech_to_text: ^7.3.0
  http: ^1.6.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1

  # CORRECTION ICI : Version compatible avec TFLite
  image_picker: ^0.8.9 
  flutter_tflite: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Déclaration des assets
  assets:
    - assets/image/
    - assets/fruit_model.tflite
    - assets/fruit_ann_model.tflite
    - assets/labels.txt